# Site settings
title: "Galaxy Belgium"
description: Belgian Galaxy Instance
email: galaxy@elixir-belgium.org
url: "https://usegalaxy.be" # the base hostname & protocol for your site, e.g. https://example.com
twitter_username: ELIXIRnodeBE
github_username:  usegalaxy-be

# Load following plugins
plugins:
  - jekyll-feed
  - jekyll/scholar
  - jekyll-twitter-plugin

# Bibliography settings
scholar:
  style: bioinformatics
  group_by: year
  order: descending
  sort_by: year
  group_order: descending


# Exclude from processing.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
